### ISSUE TITLE
Documentation update - snow.resource

### ISSUE THREAD

**Issue by fartbagxp** [rbw/aiosnow#47]
I spent a little bit of time trying to figure out why `from snow.resource import Application` from the examples wasn't working
- [app.rst](https://github.com/rbw/snow/blob/master/docs/examples/app.rst)
- [index.rst](https://github.com/rbw/snow/blob/master/docs/reference/application/index.rst)

It just turns out that it's been moved to `from snow import Application` and possibly requires a documentation change.

I learned a bunch about the library through this example - https://github.com/rbw/snow/blob/master/extras/examples/create-update-delete.py and it'll be helpful if you could write more, including how to fetch work-notes, etc.

**Comment by rbw** [comment]
You're right. Fixed in https://github.com/rbw/snow/commit/b65869684e4f9513a2d7d8fcbff24e929c24a05b.

Thanks for reporting.

> and it'll be helpful if you could write more, including how to fetch work-notes, etc.

Yep, more code examples are coming shortly, when I'm done writing tests.

**Comment by rbw** [comment]
Added an example of how to interact with the journal API (for fetching work_notes, comments etc):
https://github.com/rbw/aiosnow/blob/master/examples/table/read/journal.py

You'll need to update to the latest version to run it.
